In [2]:
import pandas as pd
import os

In [3]:
current_path = os.getcwd()
print(current_path)

/home/skyriver/project/Hokusho_Capstone/LA

In [4]:
raw_df = pd.read_csv('data/LA_givendata_sample.csv')
raw_df

,출하일자,주문Code1,Sku Code,상품명,박스당PCS,총수량,가로(mm),세로(mm),높이(mm),오더번호
0,2023.03.07,B2C(택배),W00301,艾多美 洗面乳 1瓶,40,4,143,96,132,723030501912
1,2023.03.07,B2C(택배),W00531,艾多美 愛丹 1瓶,54,5,143,96,132,723030501912
2,2023.03.07,B2C(택배),W00261,艾多美 BB霜 1瓶,91,2,143,96,132,723030503159
3,2023.03.07,B2C(택배),W00276,艾多美 凝萃煥膚防曬乳,70,4,48,23,138,723030503159
4,2023.03.07,B2C(택배),W00501,艾多美 牙膏200g(5條)*1組,10,3,143,96,132,723030503159
...,...,...,...,...,...,...,...,...,...,...
9150,2023.03.07,B2C(편의점),W00160,艾多美 益生菌 60包入,24,2,110,65,110,723030701923
9151,2023.03.07,B2C(편의점),W00266,艾多美 珠光隔離乳,70,1,38,38,130,723030703204
9152,2023.03.07,B2C(편의점),W00755,艾多美 水嫩亮白精華液,54,1,48,50,180,723030703204
9153,2023.03.07,B2C(편의점),W00531,艾多美 愛丹 1瓶,54,1,143,96,132,723030703204
9154,2023.03.07,B2C(편의점),W00288,艾多美 凝萃煥膚BB霜 No. 13,70,1,38,38,131,723030703204

### 박스 수 filtering까지 처리

In [42]:
def filter_box(df, standard):
    filtered_b2c = df[(df[standard] >= 53.41)]
    filtered_b2b = filtered_b2c[(filtered_b2c[standard] >= 55.80)]
    return filtered_b2b

In [43]:
df = raw_df.copy()
filtered_b2c_l = (raw_df['수량의 부피'] >= 53.41) & (raw_df['수량의 부피'] < 55.80)
filtered_b2b_l = (raw_df['수량의 부피'] >= 55.80)
filtered_combine_l = []
for i in zip(filtered_b2c_l, filtered_b2b_l):
    if i[0]:
        filtered_combine_l.append('*')
    elif i[1]:
        filtered_combine_l.append('**')
    else:
        filtered_combine_l.append('')
df['filtered'] = filtered_combine_l
df

,Sku Code,피킹수량,가로(mm),세로(mm),높이(mm),단위부피,수량의 부피,오더번호,filtered
0,W00301,2,143,96,132,1.81,7.26,723030501912,
1,W00531,3,143,96,132,1.81,9.07,723030501912,
2,W00261,1,143,96,132,1.81,3.63,723030503159,
3,W00276,2,48,23,138,0.15,0.61,723030503159,
4,W00501,2,143,96,132,1.81,5.44,723030503159,
...,...,...,...,...,...,...,...,...,...
9150,W00160,1,110,65,110,0.79,1.57,723030701923,
9151,W00266,1,38,38,130,0.19,0.19,723030703204,
9152,W00755,1,48,50,180,0.43,0.43,723030703204,
9153,W00531,1,143,96,132,1.81,1.81,723030703204,
9154,W00288,1,38,38,131,0.19,0.19,723030703204,

In [44]:
df['filtered'].value_counts()

      9148
**       6
*        1
Name: filtered, dtype: int64

In [45]:
def filter_box(df, standard, b2c_standard, b2b_standard):
    df = raw_df.copy()
    filtered_b2c_l = (raw_df[standard] >= b2c_standard) & (raw_df[standard] < b2b_standard)
    filtered_b2b_l = (raw_df[standard] >= b2b_standard)
    filtered_combine_l = []
    for i in zip(filtered_b2c_l, filtered_b2b_l):
        if i[0]:
            filtered_combine_l.append('*')
        elif i[1]:
            filtered_combine_l.append('**')
        else:
            filtered_combine_l.append('')
    df['box filtered'] = filtered_combine_l
    return df

In [46]:
raw_df_copy = raw_df.copy()
boxfiltered_df = filter_box(raw_df_copy, '수량의 부피', 53.41, 55.80)
boxfiltered_df

,Sku Code,피킹수량,가로(mm),세로(mm),높이(mm),단위부피,수량의 부피,오더번호,box filtered
0,W00301,2,143,96,132,1.81,7.26,723030501912,
1,W00531,3,143,96,132,1.81,9.07,723030501912,
2,W00261,1,143,96,132,1.81,3.63,723030503159,
3,W00276,2,48,23,138,0.15,0.61,723030503159,
4,W00501,2,143,96,132,1.81,5.44,723030503159,
...,...,...,...,...,...,...,...,...,...
9150,W00160,1,110,65,110,0.79,1.57,723030701923,
9151,W00266,1,38,38,130,0.19,0.19,723030703204,
9152,W00755,1,48,50,180,0.43,0.43,723030703204,
9153,W00531,1,143,96,132,1.81,1.81,723030703204,
9154,W00288,1,38,38,131,0.19,0.19,723030703204,

In [47]:
boxfiltered_df['box filtered'].value_counts()

      9148
**       6
*        1
Name: box filtered, dtype: int64

### UPDATE box numbering function

In [5]:
df = raw_df.copy()

In [ ]:
df["단위부피"] =